services:
  contabil-mongo:
    image: mongo:4.4
    container_name: contabil-mongo
    volumes:
      - contabil-mongo-data:/data/db
    networks:
      - contabil
    restart: unless-stopped

  contabil-backend:
    build: ./backend
    container_name: contabil-backend
    environment:
      MONGO_URL: mongodb://contabil-mongo:27017/contabil
      PORT: 3333
    depends_on:
      - contabil-mongo
    networks:
      - shared
      - contabil
    restart: unless-stopped

  contabil-web:
    build:
      context: ./web
      args:
        REACT_APP_API_URL: https://contabil.continuo.dev.br/api
    container_name: contabil-web
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    external: true
  contabil:
    driver: bridge

volumes:
  contabil-mongo-data:
    driver: local
